name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsspace"
database_id = "29cf0002-66d2-4c35-a12a-38886d428f6d"
